src/swexplorer/apps/characters/urls.py
from django.urls import path

from . import views

app_name = "characters"
urlpatterns = [
    path("", views.index, name="index"),
    path("dataset/<int:pk>/", views.dataset, name="dataset"),
    path("download/", views.download, name="download"),
]

src/swexplorer/conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("swexplorer.apps.characters.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

src/swexplorer/apps/characters/models.py
import os

from django.conf import settings
from django.db import models


class Dataset(models.Model):
    path = models.FilePathField(
        path=os.path.join(settings.MEDIA_ROOT, "characters"), match=r".*\.csv$", unique=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return os.path.basename(self.path)

src/swexplorer/apps/characters/views.py
import json
import uuid

import petl as etl
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render

from .models import Dataset
from .resources import get_all_results, get_planets


def index(request):
    context = {"datasets": Dataset.objects.all()}
    return render(request, "characters/index.html", context)


def dataset(request, pk):
    dataset = get_object_or_404(Dataset, pk=pk)
    table = etl.fromcsv(dataset.path)
    explore = request.GET.get("explore", [])
    fields = etl.header(table)
    limit = int(request.GET.get("limit", "10"))
    if explore:
        explore = explore.split(",")
        if len(explore) > 1:
            table = etl.aggregate(table, key=explore, aggregation=len, value=explore).rename(
                "value", "count"
            )
        show_load_more = False
    else:
        table = etl.head(table, limit)
        show_load_more = limit < len(table)
    html = etl.MemorySource()
    table.addrownumbers().tohtml(html)
    html = html.getvalue().decode().replace("class='petl'", "class='table table-striped'")
    context = {
        "dataset": dataset,
        "dataset_html": html,
        "explore": explore,
        "fields": fields,
        "limit": limit + 10,
        "show_load_more": show_load_more,
    }
    return render(request, "characters/dataset.html", context)


def download(request):
    planets = get_planets()
    source = etl.MemorySource(json.dumps(get_all_results("people")).encode())
    path = settings.MEDIA_ROOT / "characters" / f"{uuid.uuid4()}.csv"
    etl.fromjson(source).cutout(
        "films", "vehicles", "starships", "species", "created", "url"
    ).convert("homeworld", lambda v: planets[v]).convert(
        "edited", lambda v: etl.datetimeparser("%Y-%m-%dT%H:%M:%S.%fZ")(v).date()
    ).rename(
        "edited", "date"
    ).tocsv(
        path
    )
    dataset = Dataset.objects.create(path=path)
    messages.success(request, f"Added new dataset fetched on {dataset.created_at:%c}.")
    return redirect("characters:index")

src/swexplorer/apps/characters/templates/characters/dataset.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }} - Character Dataset {{ dataset }}
{% endblock title %}

{% block content %}
    <h4>
        Character Dataset {{ dataset }}<br>
        <small class="text-muted">{{ dataset.created_at }}</small>
    </h4>
    {% url "characters:dataset" dataset.pk as dataset_url %}
    <div class="btn-group" role="group" aria-label="Explore dataset">
        <small>Select fields<br>to filter by:</small>
        {% for field in fields %}
            <a
                class="btn {% if field in explore %}btn-dark{% else %}btn-light{% endif %}"
                {% if field not in explore %}
                    href="{{ dataset_url }}?explore={% if explore %}{{ explore|join:"," }},{% endif %}{{ field }}"
                {% endif %}
                role="button"
            >
                {{ field }}
            </a>
        {% endfor %}
    </div>
    {% if explore %}
        <a class="btn btn-warning" href="{{ dataset_url }}" role="button">Reset Filter</a>
    {% endif %}
    {{ dataset_html|safe }}
    {% if show_load_more %}
    <div>
        <a class="btn btn-outline-success btn-block btn-sm" href="{{ dataset_url }}?limit={{ limit }}" role="button">
            Load More
        </a>
    </div>
    {% endif %}
{% endblock content %}

src/swexplorer/apps/characters/templates/characters/index.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }} - Character Datasets
{% endblock title %}

{% block content %}
    <h1>
        Character Datasets
        <a class="btn btn-outline-success" href="{% url "characters:download" %}" role="button">
            Fetch
        </a>
    </h1>
    {% if datasets.count %}
        <table class="table table-hover table-sm">
            <tbody>
                {% for dataset in datasets %}
                    <tr>
                        <td><a href="{% url "characters:dataset" dataset.id %}">{{ dataset.created_at }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Please fetch a dataset using the green button!</p>
    {% endif %}
{% endblock content %}

src/swexplorer/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <title>{% block title %}Star Wars Explorer{% endblock title %}</title>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #aaa;">
                <a class="navbar-brand" href="{% url "characters:index" %}">
                    <img src="{% static "img/lightsaber.svg" %}" width="30" height="30" alt="Lightsaber" loading="lazy">
                    Star Wars Explorer
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" href="{% url "characters:index" %}">Characters</a>
                    </div>
                </div>
            </nav>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
            <footer>
                <small>
                    Lightsaber icon made by <a href="https://www.flaticon.com/authors/nhor-phai" title="Nhor Phai">Nhor Phai</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
                </small>
            </footer>
        </div>
        <script src="{% static "js/jquery-3.5.1.slim.min.js" %}"></script>
        <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    </body>
</html>